dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
notifications:
  email: false
deploy:
  provider: heroku
  app: septiembre-primera-prueba
  strategy: git
  api_key:
    secure: PA+3VGXBaeoBz5dypp4B4l/Sw4hZooGVl6jQN7ictD2l/BpsAEskjK2BkaPzWMKBNG7RC6yoeca9Kw1ktB1fxPcNBc9Y7g07tSOXi3RaxTLVu9KdPhDQUK+0SJfWPw2fXlSxpbrufrDPIMoAjNWrK8XLl/grUgaf1LYQAfBIQG0pHehN7ANDW99EOWAZKlRszR8Megy7oG5JP5yKLw+yep0s5P/LDGiM5EyepvXjSl2b3VoZSC2slxcdnOiJemAE/uWRt2oGin29+9YPmqWTzTpAOK5RTDQoSUBpkcmiOP2+I3sXmgFP4XqEDobYdtFAZp2fvxf/pE7fftPtxe99xiNlkQorLhnMZyNQrfEq0taKQg7NvrnN8HnqwjI49HTxMUDSJIGhHnrcVv7lVMVMWJoI/Z55ItJA+y/lEGe+BT6EhK9L7fkF4EHqusXxrB3oQRYqzHUJkPGBarVol0GzERX9fQxcx5NbpXyXSi1FfJcTUATtw0QwUdzk/PpQCvNreftYWg1Xy0BKGQwIKFkupTFZ4MQ5Z10RiIeB32q/pgzCCRgYm447fqln8jf1M+E67AciAxux4sb1o4OJR+qnsIJo64jjrG16/mEa/fCu1jl4F+bT06/VEtOyZyYMHKEut2Fi7B3PJHieRs2GoD6LJLFiCO+b9ZmucHyFBGuzlfY=
